import "./globals.css"
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import Navbar from "@/components/Navbar"

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Mon portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body
        className={montserrat.className + " antialiased scroll-smooth pt-20"}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
